config/routes.rb
Rails.application.routes.draw do

	root'books#top'
	get '/home/about', to: 'books#about'
  get '/search', to: 'search#search'
  devise_for :users
  resources :books, only:[:new, :create, :index, :show, :destroy,:edit,:update] do
	  resource :favorites, only: [:create, :destroy]
	  resource :book_comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:index, :create, :destroy]
  resources :users, only:[:new,:index,:show, :update, :edit] do
  	 member do
     get :followings, :followers
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
    has_many :favorites, dependent: :destroy
    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
	has_many :book_comments, dependent: :destroy
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user
    belongs_to :book
    validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attachment :profile_image

  has_many :books
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :name, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}

  # 能動的関係
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  # 受動的関係
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	 protect_from_forgery with: :exception
	 before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email,:password,:password_confirmation])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	def create
	    book = Book.find(params[:book_id])
	    comment = current_user.book_comments.new(book_comment_params)
	    comment.book_id = book.id
	    comment.save
	    redirect_to book_path(book)
	end
	def destroy
	    comment = BookComment.find(params[:book_id])
	    book = comment.book
	    comment.destroy
	    redirect_to book_path(book)
    end
	private
	def book_comment_params
	    params.require(:book_comment).permit(:user_id,:book_id,:comment)
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :authenticate_user!, except:[:top, :about]

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @post = Book.new
    @book_comment = BookComment.new

  end

  def top
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

   if @book.save
      flash[:success] = "successfully"
      redirect_to @book
    else
      flash[:danger] = @book.errors.full_messages
      @books = Book.all
      render 'index'
    end
  end


  def edit
    @book = Book.find(params[:id])
    if current_user.id != @book.user_id
      redirect_to books_path
    end
  end

  def about
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:success] = "successfully"
    redirect_to @book
    else
      flash[:danger] = @book.errors.full_messages
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title,:body)

  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
	    book = Book.find(params[:book_id])
	    favorite = current_user.favorites.new(book_id: book.id)
	    favorite.save
	    redirect_back fallback_location: @book
	end
	def destroy
	    book = Book.find(params[:book_id])
	    favorite = current_user.favorites.find_by(book_id: book.id)
	    favorite.destroy
	    redirect_back fallback_location: @book
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  # before_action :ensure_correct_user(params[:id]), {only: [:edit, :update, :destroy]}

  def show
  	@user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def create
      @book.user_id = current_user.id
      @book = Book.new(book_params)
   if @book.save
   flash[:success] = "You have creatad user successfully."
      redirect_to @book
    else
   flash[:danger] = @book.errors.full_messages
      @books = Book.all
      render 'index'
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if current_user.id != @user.id
      redirect_to user_path(current_user)
    end
  end

  def update
    if current_user
       @user = User.find(params[:id])
       if @user.update(user_params)
       	flash[:success] = "You have updated user successfully."
          redirect_to user_path(@user.id)
         else
          flash[:danger] = @user.errors.full_messages
          render "edit"
       end
     else
    end
   end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_side.html.erb
<h1>New book</h1>
<%= form_for(book, url: books_path)do |f| %>
<% if @book.errors.any? %>
<%= @book.errors.count %>errors
<ul>
 <% @book.errors.full_messages.each do |message| %>
 <li><%= message %></li>
 <% end %>
</ul>
<% end %>

<%= f.label :title %>
<%= f.text_field :title, class: "form-control book_title"%>
<%= f.label :opinion %>
<%= f.text_area :body, class: "form-control book_body" %>
<%= f.submit class: "btn btn-block btn-primary" %>
<% end %>

app/views/books/about.html.erb
<h2>welcome to<span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers  !!</strong></h2>

app/views/books/edit.html.erb
<div class="container">
<div class="row">
<div class="col-md-8 col-md-offset-2">

<h2>Editing Book</h2>

<%= form_for @book do |f| %>

<% if @book.errors.any? %>
<%= @book.errors.count %>errors
<ul>
  <% @book.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>



<div class="form-group">
  <%= f.label :title %><br>
  <%= f.text_field :title, autofocus: true ,class: "form-control book_title"%>
</div>

<div class="form-group">
  <%= f.label :opinion %><br />
  <%= f.text_area :body, autofocus: true ,class: "form-control book_body"%>
</div>

<div class="actions">
  <%= f.submit "Update book", class: "btn btn-primary" %>
</div>
<% end %>

<%= link_to "Show", book_path(@book) %> |
<%= link_to "Back", books_path %>

</div>
</div>
</div>

app/views/books/index.html.erb
<div class="container">
<div class="row">
<div class="col-md-4">
  <%= render 'users/info',{user:current_user} %>

  <%= render 'side',{book:@book, user:current_user} %>
</div>

<div class="col-md-8">
<table class="table">
  <h1>Books</h1>

  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <% @books.each do |book| %>
  <tbody>
    <tr>
      <td>
        <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format:'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %>
      </td>
      <td><%=link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
      <td><%= book.body %></td>
      <td>
        <% if book.favorited_by?(current_user) %>
        <%= link_to book_favorites_path(book), method: :delete do %>
        <i><span class="glyphicon glyphicon-heart" aria-hidden="true"></span></i>
        <%= book.favorites.count %>
        <% end %>
        <% else %>
        <%= link_to book_favorites_path(book), method: :post do %>
        <i><span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span></i>
        <%= book.favorites.count %>
        <% end %>
        <% end %>
      </td>
      <td><%= link_to "コメント数：#{book.book_comments.count}", book_path(book.id) %></td>
      <% end %>
    </tr>
  </tbody>
</table>

</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container">
<div class="row">
<div class="col-md-4">
  <%= render 'users/info',{user:@book.user} %>
  <%= render 'side',{book:@post, user:@book.user} %>
</div>

<div class="col-md-8">
<table class="table">
  <h1>Book detail</h1>

  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
    </tr>
  </thead>
    <tr>
      <th>
        <%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50, format:'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %>
        <%= link_to @user.name ,user_path(@user.id) %>
      </th>
      <th><%= @book.title %></th>
      <th><%= @book.body %></th>
      <% if @book.favorited_by?(current_user) %>
      <th>
        <%= link_to book_favorites_path(@book), method: :delete do %>
        <i><span class="glyphicon glyphicon-heart" aria-hidden="true"></span></i>
        <%= @book.favorites.count %>
      </th>
        <% end %>
        <% else %>
      <th>
        <%= link_to book_favorites_path(@book), method: :post do %>
        <i><span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span></i>
        <%= @book.favorites.count %>
        <% end %>
      </th>
      <% end %>

      <% if @book.user == current_user %>
      <td>
        <button type="button" class="btn btn-info"><%= link_to "edit",edit_book_path, class: "edit_book_#{@book.id}" %></button>
      </td>
      <td>
        <button type="button" class="btn btn-danger"><%= link_to "Destroy",book_path,method: :delete, class: "destroy_book_#{@book.id}" %></button>
      </td>
      <% end %>
    </tr>
</table>

<div class="comment-list bt style-2" id="comments">
<div class="float-wrapper">

</div>

<ol>
  <% @book.book_comments.each do |book_comment| %>
  <div class="comment-body bb">
    <div class="comment-text">
      <div class="comment-author clearfix">
        <%= attachment_image_tag(@book.user, :profile_image, :fill, 25, 25, format:'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg", size:'50x50') %>
        <%= book_comment.comment %>
        <% if book_comment.user == current_user %>
        <%= link_to "Destroy", book_book_comments_path(book_comment), method: :delete, class: "btn btn-danger" %>
        <% end %>
      </div>
      <div><%= link_to @user.name ,user_path(@user.id) %></div>
    </div>
  </div>
  <% end %>
</ol>

<%= form_for [@book, @book_comment] do |f| %>
<div class="row">
<div class="col-sm-12">
  <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメント" %><br />
</div>
</div>
<%= f.submit "送信", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>
<% if @book_comment.user == current_user %>
<td>
  <button type="button" class="btn btn-danger"><%= link_to "Destroy", book_book_comment_path(@book, book_comment), method: :delete, remote: true, class: "btn btn-danger" %></button>
</td>
<% end %>

</div>
</div>
</div>

app/views/books/top.html.erb
<div class="container">
<div class="row">
<div class="main col-md-offset-3 col-md-6">

<h2>welcome to<span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers  !!</strong></h2>
<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers,</strong><br>you can share and exchange your opinions , inpressions , and emotions<br>about various books!</p>

<%= link_to "Log in",new_user_session_path, class: "sign_in btn btn-info col-xs-10 col-xs-offset-1" %>
<%= link_to "Sign up",new_user_registration_path, class: "sign_up btn btn-success col-xs-10 col-xs-offset-1" %>

</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <header>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand col-md-4">Bookers</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li><%= link_to 'Home', user_path(current_user), class: "home glyphicon glyphicon-home" %></li>
          <li><%= link_to 'Users', users_path, class: "users glyphicon glyphicon-user" %></li>
          <li><%= link_to 'Books', books_path, class: "books glyphicon glyphicon-book" %></li>
          <li><%= link_to "Log out",destroy_user_session_path,method: :delete, class: "logout glyphicon glyphicon-log-out" %></li>
          <% else %>
          <li><%= link_to 'Home', root_path, class: "home glyphicon glyphicon-home" %></li>
          <li><%= link_to 'About', home_about_path, class: "about glyphicon glyphicon-link" %></li>
          <li><%= link_to "Sign up",new_user_registration_path, class: "sign_up glyphicon glyphicon-edit" %></li>
          <li><%= link_to 'Log in', new_user_session_path, class: "sign_in glyphicon glyphicon-log-in" %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <h3>Bookers</h3>
  </header>

  <% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>

  <%= yield %>
  <div class="row">
  <div class="col-xs-3 col-xs-offset-9">
    <p>CopyRight Infratop.inc</p>
  </div>
  </div>
</body>

</html>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<h1>User info</h1>
<div>
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format:'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %>
</div>

<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>

<% if user == current_user %>
<%= link_to '',edit_user_path(current_user.id),class: "btn btn-block btn-default glyphicon glyphicon-wrench edit_user_#{current_user.id}" %>
<% end %>





app/views/users/edit.html.erb
<h1>Users info</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
  <%= @user.errors.count %>errors
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="form-group">
  <%= f.label :name %><br>
  <%= f.text_field :name, autofocus: true ,class: "form-control name"%>
</div>

<div class="form-group">
  <%= f.label :image %><br />
  <%= f.attachment_field :profile_image,class: "user_image" %>
</div>

<div class="form-group">
  <%= f.label :introduction %><br />
  <%= f.text_area :introduction, autofocus: true ,class: "form-control introduction"%>
</div>

<div class="actions">
  <%= f.submit "Update User", class: "btn btn-primary" %>
</div>
<% end %>
<br />

<%= link_to "Back", books_path %>

app/views/users/index.html.erb
<div class="container">
<div class="row">
<div class="col-md-4">
  <%= render 'info',{user:current_user} %>
  <%= render 'books/side',{book:@book, user:current_user} %>
</div>

<div class="col-md-8">
  <table class="table">
    <h1>Users</h1>
    <thead>
      <tr>
        <th>Image</th>
        <th>name</th>
      </tr>
    </thead>

    <% @users.each do |user| %>
    <tbody>
      <tr>
        <td>
          <div><%= attachment_image_tag user, :profile_image, :fill, 50, 50, format:'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %></div>
        </td>
        <td><%= user.name %></td>
        <td><%= link_to "show",user_path(user.id), class: "user_#{user.id}" %></td>
      </tr>
    </tbody>
    <% end %>
  </table>
</div>

</div>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="row">
<div class="col-md-4">
  <%= render 'info',{user: @user} %>
  <%= render 'books/side',{book:@book, user:current_user} %>
</div>

<div class="col-md-8">
  <table class="table">
    <h1>Books</h1>
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
      </tr>
    </thead>

    <% @books.each do |book| %>
    <tbody>
      <tr>
        <td>
          <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format:'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %>
        </td>
        <td><%=link_to book.title, book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td>
          <% if book.favorited_by?(current_user) %>
          <%= link_to book_favorites_path(book), method: :delete do %>
          <i><span class="glyphicon glyphicon-heart" aria-hidden="true"></span></i>
          <%= book.favorites.count %>
          <% end %>
          <% else %>
          <%= link_to book_favorites_path(book), method: :post do %>
          <i><span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span></i>
          <%= book.favorites.count %>
          <% end %>
          <% end %>
        </td>
        <td><%= link_to "コメント数：#{book.book_comments.count}", book_path(book.id) %></td>
          <% end %>
      </tr>
    </tbody>
  </table>
</div>

</div>
</div>